enum ReaderPreferenceKeys {
    static let preferenceVersion = "reader.preferenceVersion"
    static let fontFamily = "reader.fontFamily"
    static let fontSize = "reader.fontSize"
    static let lineSpacing = "reader.lineSpacing"
    static let paragraphSpacing = "reader.paragraphSpacing"
    static let contentWidth = "reader.contentWidth"
    static let horizontalPadding = "reader.horizontalPadding"
    static let theme = "reader.theme"
    static let paragraphIndent = "reader.paragraphIndent"
    static let continuousReading = "reader.continuousReading"
    static let pageTurnMode = "reader.pageTurnMode"
    static let mangaPageTurnMode = "reader.mangaPageTurnMode"
    static let mangaPageLayout = "reader.mangaPageLayout"
    static let mangaTabletAutoLandscape = "reader.mangaTabletAutoLandscape"
    static let mangaFirstPageAlone = "reader.mangaFirstPageAlone"
    static let mangaDarkBackground = "reader.mangaDarkBackground"
    static let prefetchNext = "reader.prefetchNext"
    static let lastReadingBookID = "reader.lastReadingBookID"
    static let lastReadingChapterID = "reader.lastReadingChapterID"
    static let presentationMode = "reader.presentationMode"
    static let academicColumnMode = "reader.academicColumnMode"
    static let academicModeShortcut = "reader.academicModeShortcut"
}
