import Foundation
import Observation
@preconcurrency import WebKit

@MainActor
@Observable
final class WebKitHostSession: NSObject {
    let host: String
    let webView: WKWebView
    private let loadTimeout: Duration
    private(set) var status = "等待浏览器请求…"
    private(set) var failureMessage: String?

    @ObservationIgnored
    var onVerificationRequired: (@MainActor (WebKitHostSession, URL) -> Void)?
    @ObservationIgnored
    var onVerificationCompleted: (@MainActor (WebKitHostSession) -> Void)?

    @ObservationIgnored
    private var queuedLoads: [QueuedLoad] = []
    @ObservationIgnored
    private var activeLoad: QueuedLoad?
    @ObservationIgnored
    private var activeNavigation: WKNavigation?
    @ObservationIgnored
    private var activeTimeoutTask: Task<Void, Never>?
    @ObservationIgnored
    private var inspectingLoadID: UUID?
    /// Nodes resolved for the page currently loaded, dropped when a new page starts.
    @ObservationIgnored
    private var resolvedImageNodes: [String: ResolvedImageNode] = [:]
    @ObservationIgnored
    private var documentIsReady = false
    @ObservationIgnored
    private(set) var hasReadMangaImages = false
    var isIdle: Bool { activeLoad == nil && queuedLoads.isEmpty }
    @ObservationIgnored
    private let blobLocator = MangaBlobRegionLocator()

    init(
        host: String,
        websiteDataStore: WKWebsiteDataStore = .default(),
        loadTimeout: Duration = .seconds(30),
        webView suppliedWebView: WKWebView? = nil
    ) {
        self.host = host.lowercased()
        self.loadTimeout = loadTimeout
        if let suppliedWebView {
            webView = suppliedWebView
        } else {
            let configuration = WKWebViewConfiguration()
            configuration.websiteDataStore = websiteDataStore
            // This site's normal lazy loader needs a viewport to materialize the
            // requested blob. It remains an invisible data source, not reader UI.
            let frame = DuokanMangaAdapter.supportsHost(host)
                ? CGRect(x: 0, y: 0, width: 800, height: 1000) : .zero
            webView = WKWebView(frame: frame, configuration: configuration)
        }
        super.init()
        webView.navigationDelegate = self
    }

    func load(_ url: URL) async throws -> LoadedHTML {
        try Task.checkCancellation()
        let id = UUID()
        return try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                queuedLoads.append(QueuedLoad(id: id, url: url, completion: .document(continuation)))
                startNextLoadIfNeeded()
            }
        } onCancel: {
            Task { @MainActor [weak self] in
                self?.cancelLoad(id: id)
            }
        }
    }

    func isDisplaying(_ url: URL) -> Bool {
        documentIsReady && webView.url.map { URLCanonicalizer.canonicalString($0.absoluteString) }
            == URLCanonicalizer.canonicalString(url.absoluteString)
    }

    func readMangaImage(_ imageURL: URL, chapterURL: URL) async throws -> MangaImageReadResult {
        try Task.checkCancellation()
        let id = UUID()
        return try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                queuedLoads.append(QueuedLoad(id: id, url: chapterURL, completion: .image(imageURL, continuation)))
                startNextLoadIfNeeded()
            }
        } onCancel: {
            Task { @MainActor [weak self] in self?.cancelLoad(id: id) }
        }
    }

    func reloadForVerification() {
        failureMessage = nil
        status = "正在重新载入验证页面…"
        if let url = activeLoad?.url {
            activeNavigation = webView.load(URLRequest(url: url))
            scheduleTimeout(for: activeLoad?.id)
        }
    }

    func cancelCurrentLoad() {
        guard let activeLoad else { return }
        invalidateImageRequest(activeLoad)
        webView.stopLoading()
        cancelActiveTimeout()
        self.activeLoad = nil
        activeNavigation = nil
        activeLoad.completion.fail(HTMLLoadError.cancelled)
        startNextLoadIfNeeded()
    }

    func failCurrentLoad(_ error: any Error) {
        guard let activeLoad else { return }
        invalidateImageRequest(activeLoad)
        webView.stopLoading()
        cancelActiveTimeout()
        self.activeLoad = nil
        activeNavigation = nil
        failureMessage = error.localizedDescription
        activeLoad.completion.fail(error)
        startNextLoadIfNeeded()
    }

    private func invalidateImageRequest(_ load: QueuedLoad) {
        guard case .image = load.completion else { return }
        // UUID is generated by the app; matching prevents a late cancellation
        // from invalidating a newer script in the same page.
        webView.evaluateJavaScript("if (globalThis.__yyreaderImageRequest === '\(load.id.uuidString)') globalThis.__yyreaderImageRequest = null;") { _, _ in }
    }

    private func startNextLoadIfNeeded() {
        guard activeLoad == nil, !queuedLoads.isEmpty else { return }
        let next = queuedLoads.removeFirst()
        activeLoad = next
        if case .image = next.completion { hasReadMangaImages = true }
        failureMessage = nil
        status = "正在通过浏览器载入网页…"
        scheduleTimeout(for: next.id)
        if case let .image(url, _) = next.completion, MangaBlobSource(url: url) != nil {
            webView.frame = CGRect(x: 0, y: 0, width: 800, height: 1000)
        }
        if case .image = next.completion, isDisplaying(next.url) {
            Task { @MainActor [weak self] in await self?.inspectFinishedPage() }
        } else {
            documentIsReady = false
            activeNavigation = webView.load(URLRequest(url: next.url))
        }
    }

    private func cancelLoad(id: UUID) {
        if activeLoad?.id == id {
            cancelCurrentLoad()
            return
        }
        guard let index = queuedLoads.firstIndex(where: { $0.id == id }) else { return }
        let queued = queuedLoads.remove(at: index)
        queued.completion.fail(HTMLLoadError.cancelled)
    }

    private func inspectFinishedPage() async {
        guard let activeLoad, inspectingLoadID != activeLoad.id else { return }
        inspectingLoadID = activeLoad.id
        defer {
            if inspectingLoadID == activeLoad.id { inspectingLoadID = nil }
        }
        do {
            let reusePage = documentIsReady && isDisplaying(activeLoad.url)
            var html: String?
            if !reusePage || activeLoad.completion.isDocument {
                _ = try await webView.callAsyncJavaScript(CatalogExpansionScripts.expand,
                    arguments: [:], in: nil, contentWorld: .page)
                guard self.activeLoad?.id == activeLoad.id else { return }
                if try await webView.evaluateJavaScript(MangaSnapshotScripts.hasPendingReader) as? Bool == true {
                    guard self.activeLoad?.id == activeLoad.id else { return }
                    webView.frame = CGRect(x: 0, y: 0, width: 800, height: 1000)
                    _ = try await webView.callAsyncJavaScript(MangaSnapshotScripts.waitForImages,
                        arguments: [:], in: nil, contentWorld: .page)
                }
                guard self.activeLoad?.id == activeLoad.id else { return }
                let result = try await webView.evaluateJavaScript(MangaSnapshotScripts.capture)
                guard self.activeLoad?.id == activeLoad.id else { return }
                guard let captured = result as? String, !captured.isEmpty else { throw HTMLLoadError.invalidResponse }
                html = captured
                if HTMLChallengeDetector.isChallenge(captured) {
                    cancelActiveTimeout()
                    status = "网站要求人工验证，请在验证窗口中完成操作…"
                    onVerificationRequired?(self, webView.url ?? activeLoad.url)
                    return
                }
                await synchronizeCookies(for: webView.url ?? activeLoad.url)
                guard self.activeLoad?.id == activeLoad.id else { return }
                onVerificationCompleted?(self)
            }
            guard let finalURL = webView.url else { throw HTMLLoadError.invalidResponse }
            switch activeLoad.completion {
            case let .document(continuation):
                guard let html else { throw HTMLLoadError.invalidResponse }
                documentIsReady = true
                finish(activeLoad.id)
                continuation.resume(returning: LoadedHTML(requestedURL: activeLoad.url, finalURL: finalURL,
                                                          html: html, retrievalKind: .webKit))
            case let .image(imageURL, continuation):
                let result = try await readImage(imageURL, chapterURL: activeLoad.url, loadID: activeLoad.id)
                guard self.activeLoad?.id == activeLoad.id else { return }
                documentIsReady = true
                finish(activeLoad.id)
                continuation.resume(returning: result)
            }
            startNextLoadIfNeeded()
        } catch {
            guard self.activeLoad?.id == activeLoad.id else { return }
            failCurrentLoad(error)
        }
    }

    private func readImage(_ imageURL: URL, chapterURL: URL, loadID: UUID) async throws -> MangaImageReadResult {
        let source = MangaBlobSource(url: imageURL)
        var expectedCount: Int?
        for attempt in 0..<2 {
            guard activeLoad?.id == loadID else { throw HTMLLoadError.cancelled }
            var domIndex = -1
            var nodeID = ""
            var expectedBlobURL = ""
            if let source {
                // Reading a chapter resolves every page against the same loaded
                // document, so the node found for a page is affirmed cheaply before
                // paying for another clone, parse and region-scoring pass. A missing
                // or changed node falls through to the full re-score below.
                if attempt == 0, let resolved = await affirmedNode(for: imageURL, chapterURL: chapterURL, loadID: loadID) {
                    if let url = resolved.directURL { return .address(url) }
                    domIndex = resolved.domIndex; nodeID = resolved.nodeID; expectedBlobURL = resolved.expectedBlobURL
                } else {
                let snapshot = try await webView.evaluateJavaScript(MangaSnapshotScripts.capture)
                guard activeLoad?.id == loadID, let html = snapshot as? String, let finalURL = webView.url else {
                    throw HTMLLoadError.cancelled
                }
                let location = try await blobLocator.locate(source, in: LoadedHTML(requestedURL: chapterURL,
                    finalURL: finalURL, html: html, retrievalKind: .webKit))
                guard activeLoad?.id == loadID else { throw HTMLLoadError.cancelled }
                if let expectedCount, expectedCount != location.pageCount { throw NovelParsingError.noMangaImages }
                expectedCount = location.pageCount
                if let url = location.directURL { return .address(url) }
                resolvedImageNodes[imageURL.absoluteString] = ResolvedImageNode(
                    pageURL: finalURL,
                    chapterURL: chapterURL.absoluteString,
                    nodeID: location.nodeID,
                    location: location
                )
                domIndex = location.domIndex; nodeID = location.nodeID; expectedBlobURL = location.expectedBlobURL
                }
            }
            do {
                let result = try await webView.callAsyncJavaScript(MangaBlobScripts.readImage,
                    arguments: ["imageURL": imageURL.absoluteString, "chapterURL": chapterURL.absoluteString,
                                "domIndex": domIndex, "nodeID": nodeID, "expectedBlobURL": expectedBlobURL,
                                "requestID": loadID.uuidString], in: nil, contentWorld: .page)
                guard activeLoad?.id == loadID, let encoded = result as? String, !encoded.isEmpty else {
                    throw HTMLLoadError.cancelled
                }
                return .encoded(encoded)
            } catch {
                let message = (error as NSError).userInfo["WKJavaScriptExceptionMessage"] as? String ?? ""
                guard source != nil, attempt == 0, activeLoad?.id == loadID,
                      message.contains("Image element replaced") || message.contains("Image changed") else { throw error }
                // Public lazy loaders replace placeholder img nodes. Re-score
                // once, retaining page count, rather than waiting on a dead node.
                try await Task.sleep(for: .milliseconds(150))
            }
        }
        throw HTMLLoadError.invalidResponse
    }

    /// Where a page of the current chapter was found in the loaded document.
    private struct ResolvedImageNode {
        let pageURL: URL
        let chapterURL: String
        let nodeID: String
        let location: MangaBlobRegionLocator.Location
    }

    /// Affirm a previously resolved page without re-scoring the document: the
    /// document must still be the one that was scored, and the node must still
    /// exist with the source the reader was told about.
    private func affirmedNode(for imageURL: URL, chapterURL: URL, loadID: UUID) async -> MangaBlobRegionLocator.Location? {
        guard let resolved = resolvedImageNodes[imageURL.absoluteString],
              let pageURL = webView.url,
              resolved.pageURL == pageURL,
              resolved.chapterURL == chapterURL.absoluteString,
              !resolved.nodeID.isEmpty,
              activeLoad?.id == loadID else { return nil }
        let current = try? await webView.callAsyncJavaScript(
            MangaBlobScripts.confirmNode,
            arguments: ["nodeID": resolved.nodeID],
            in: nil,
            contentWorld: .page
        )
        guard activeLoad?.id == loadID, let source = current as? String, !source.isEmpty else { return nil }
        if !resolved.location.expectedBlobURL.isEmpty, source != resolved.location.expectedBlobURL { return nil }
        return resolved.location
    }

    private func finish(_ id: UUID) {
        guard activeLoad?.id == id else { return }
        cancelActiveTimeout()
        activeLoad = nil
        activeNavigation = nil
        status = "网页载入完成"
    }

    private func synchronizeCookies(for url: URL) async {
        guard let targetHost = url.host?.lowercased() else { return }
        let cookies = await allCookies()
        for cookie in cookies where cookieMatches(cookie, host: targetHost) {
            HTTPCookieStorage.shared.setCookie(cookie)
        }
    }

    private func allCookies() async -> [HTTPCookie] {
        await withCheckedContinuation { continuation in
            webView.configuration.websiteDataStore.httpCookieStore.getAllCookies { cookies in
                continuation.resume(returning: cookies)
            }
        }
    }

    private func cookieMatches(_ cookie: HTTPCookie, host: String) -> Bool {
        let cookieDomain = cookie.domain
            .trimmingCharacters(in: CharacterSet(charactersIn: "."))
            .lowercased()
        return host == cookieDomain || host.hasSuffix(".\(cookieDomain)")
    }

    private func scheduleTimeout(for loadID: UUID?) {
        cancelActiveTimeout()
        guard let loadID else { return }
        activeTimeoutTask = Task { @MainActor [weak self] in
            guard let self else { return }
            do {
                try await Task.sleep(for: loadTimeout)
            } catch {
                return
            }
            guard activeLoad?.id == loadID else { return }
            failCurrentLoad(HTMLLoadError.requestTimedOut)
        }
    }

    private func cancelActiveTimeout() {
        activeTimeoutTask?.cancel()
        activeTimeoutTask = nil
    }
}

extension WebKitHostSession: WKNavigationDelegate {
    func webView(_ webView: WKWebView, didStartProvisionalNavigation navigation: WKNavigation?) {
        guard activeLoad != nil else { return }
        // A new document invalidates every node resolved in the previous one.
        resolvedImageNodes.removeAll()
        activeNavigation = navigation
        documentIsReady = false
        failureMessage = nil
        status = "正在连接网站…"
    }

    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation?) {
        guard activeLoad != nil, navigation === activeNavigation else { return }
        Task { @MainActor [weak self] in
            await self?.inspectFinishedPage()
        }
    }

    func webView(
        _ webView: WKWebView,
        didFailProvisionalNavigation navigation: WKNavigation?,
        withError error: any Error
    ) {
        guard navigation === activeNavigation else { return }
        failNavigation(error)
    }

    func webView(_ webView: WKWebView, didFail navigation: WKNavigation?, withError error: any Error) {
        guard navigation === activeNavigation else { return }
        failNavigation(error)
    }

    func webViewWebContentProcessDidTerminate(_ webView: WKWebView) {
        documentIsReady = false
        failCurrentLoad(HTMLLoadError.verificationFailed("浏览器内容进程已停止。"))
    }

    private func failNavigation(_ error: any Error) {
        if let urlError = error as? URLError, urlError.code == .cancelled { return }
        failCurrentLoad(error)
    }
}

private extension WebKitHostSession {
    struct QueuedLoad {
        let id: UUID
        let url: URL
        let completion: Completion
    }

    enum Completion {
        case document(CheckedContinuation<LoadedHTML, any Error>)
        case image(URL, CheckedContinuation<MangaImageReadResult, any Error>)
        var isDocument: Bool { if case .document = self { true } else { false } }
        func fail(_ error: any Error) {
            switch self {
            case let .document(continuation): continuation.resume(throwing: error)
            case let .image(_, continuation): continuation.resume(throwing: error)
            }
        }
    }
}
